version: "3"
services:
  jenkins:
      networks:
          - test_default
      image: jenkinsci/blueocean
      user: root
      ports:
           - "8080:8080"
      volumes:
           - "/var/run/docker.sock:/var/run/docker.sock"
           - "${HOME}:/home"
           - "jenkins-data:/var/jenkins_home"

  artifactory:
      networks:
          - test_default
      image: "docker.bintray.io/jfrog/artifactory-oss:latest"
      user: root
      ports:
           - "8081:8081"
      volumes:
           - "artifactory5_data:/var/opt/jfrog/artifactory"
      
volumes:
     jenkins-data:
     artifactory5_data:

networks:
   test_default:
